### ISSUE TITLE
classification failed on gke cluster

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/sveltos-agent#143]
1. Created a GKE cluster running Kubernetes version

2. Applied Classifier
```yaml
apiVersion: lib.projectsveltos.io/v1alpha1
kind: Classifier
metadata:
  name: v1-27
spec:
  classifierLabels:
  - key: version
    value: v1-27
  kubernetesVersionConstraints:
  - comparison: GreaterThanOrEqualTo
    version: 1.27.0
```

3. Cluster was not classified as a match

I0804 09:05:36.270119       1 classifier_evaluation.go:94] "evaluating" classifier="v1-27"
I0804 09:05:36.274064       1 utils.go:50] "cluster version: v1.27.2-gke.1200"
I0804 09:05:36.274128       1 classifier_evaluation.go:152] "cluster version v1.27.2-gke.1200"
I0804 09:05:36.274284       1 classifier_evaluation.go:122] "isMatch false" classifier="v1-27"
I0804 09:05:36.274351       1 classifier_evaluation.go:522] "creating ClassifierReport" classifier="v1-27"

Method: isVersionAMatch needs to be fixed.
